### ISSUE TITLE
failed to reload after change mofification

### ISSUE THREAD

**Issue by Paul75** [camesine/Typescript-restful-starter#10]
Hello,

When I start 'npm run dev', it works but if I modify a script it want to reload but crash : 
```
...
Error: bind EADDRINUSE null:3000
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at listenOnMasterHandle (net.js:1411:16)
    at rr (internal/cluster/child.js:111:12)
    at Worker.send (internal/cluster/child.js:78:7)
    at process.onInternalMessage (internal/cluster/utils.js:42:8)
    at emitTwo (events.js:131:20)
    at process.emit (events.js:214:7)
    at process.emit (/Users/far-paul/Sites/GOMPOST/server2/node_modules/source-map-support/source-map-support.js:453:21)
    at emit (internal/child_process.js:772:12)
Worker 63493 died with code: 1, and signal: null
Starting a new worker
Error: bind EADDRINUSE null:3000
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at listenOnMasterHandle (net.js:1411:16)
    at rr (internal/cluster/child.js:111:12)
    at Worker.send (internal/cluster/child.js:78:7)
    at process.onInternalMessage (internal/cluster/utils.js:42:8)
    at emitTwo (events.js:131:20)
    at process.emit (events.js:214:7)
    at process.emit (/Users/far-paul/Sites/GOMPOST/server2/node_modules/source-map-support/source-map-support.js:453:21)
    at emit (internal/child_process.js:772:12)
Worker 63492 died with code: 1, and signal: null
Starting a new worker
Error: bind EADDRINUSE null:3000
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at listenOnMasterHandle (net.js:1411:16)
    at rr (internal/cluster/child.js:111:12)
    at Worker.send (internal/cluster/child.js:78:7)
    at process.onInternalMessage (internal/cluster/utils.js:42:8)
    at emitTwo (events.js:131:20)
    at process.emit (events.js:214:7)
    at process.emit (/Users/far-paul/Sites/GOMPOST/server2/node_modules/source-map-support/source-map-support.js:453:21)
    at emit (internal/child_process.js:772:12)
Worker 63494 died with code: 1, and signal: null
Starting a new worker
...
```

And it not stop I must kill process ....

Thanks for help.

**Comment by camesine** [comment]
Fixed

**Comment by Paul75** [comment]
Thanks a lot ....

I test it and seems works

**Comment by Paul75** [comment]
It same error today ....

Very strange .... I must kill all process of node .... and after restart works ....

Not see why di this ....

**Comment by camesine** [comment]
What i'ts your node version? or other specification? I don't have that error.. It's very strange :/

**Comment by Paul75** [comment]
Node is 8.9.4 ....

On Mac OS X 10.13.3....
