### ISSUE TITLE
bug launch in the last relase

### ISSUE THREAD

**Issue by Paul75** [camesine/Typescript-restful-starter#29]
Hello,

When take last version (clone) and do npm run dev I've got : 
```
if (!options || !options.secret) throw new Error('secret should be set');
                                         ^
Error: secret should be set
```

Thanks

**Comment by Paul75** [comment]
npm start also failed ....

**Comment by camesine** [comment]
I added dotenv dependency and .env file where i set that secret.. do you executed npm install with this dependency?

**Comment by Paul75** [comment]
yes I execute npm install ....

when npm start : 

```
>   "C:\www\lucy\heberge_extraction\he_server-test\node_modules\.bin\\node.exe"  "C:\www\lucy\heberge_extraction\he_server-test\node_modules\.bin\\..\cross-env\dist\bin\cross-env.js" NODE_ENV=PRODUCTION node -r dotenv/config Index.js dotenv_config_path=$(pwd)/.env
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! typescript-restful-starter@0.1.0 start: `npm run build && cd dist && cross-env NODE_ENV=PRODUCTION node -r dotenv/config Index.js dotenv_config_path=$(pwd)/.env`
npm ERR! Exit status 255
npm ERR!
npm ERR! Failed at the typescript-restful-starter@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\pkbp512\AppData\Roaming\npm-cache\_logs\2018-12-11T08_01_25_373Z-debug.log
```

when npm run dev : 
```
npm run dev

> typescript-restful-starter@0.1.0 dev C:\www\lucy\heberge_extraction\he_server-test
> nodemon

[nodemon] 1.18.7
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: **/*.ts
[nodemon] starting `node -r ts-node/register -r dotenv/config Index.ts dotenv_config_path=$(pwd)/.env`

C:\www\lucy\heberge_extraction\he_server-test\node_modules\express-jwt\lib\index.js:20
  if (!options || !options.secret) throw new Error('secret should be set');
                                         ^
Error: secret should be set
    at module.exports (C:\www\lucy\heberge_extraction\he_server-test\node_modules\express-jwt\lib\index.js:20:42)
    at Object.<anonymous> (C:\www\lucy\heberge_extraction\he_server-test\config\Router.ts:22:9)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Module.m._compile (C:\www\lucy\heberge_extraction\he_server-test\node_modules\ts-node\src\index.ts:439:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Object.require.extensions.(anonymous function) [as .ts] (C:\www\lucy\heberge_extraction\he_server-test\node_modules\ts-node\src\index.ts:442:12)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
```

Thanks

**Comment by camesine** [comment]
You're using windows, the config path dotenv_config_path=$(pwd)/.env the most likely is then this has a problem

**Comment by Paul75** [comment]
yes I use windows 10 ...

**Comment by camesine** [comment]
I modified dontenv configuration to fix this

**Comment by Paul75** [comment]
works now. thanks
